sonar.projectKey=clinic-frontend
sonar.projectName=Clinic frontend
sonar.sources=app,api,components,features
sonar.exclusions=**/*.test.ts,**/*.test.tsx,api/schema.d.ts,api/openapi.json
sonar.tests=api,features,test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
