services:
  mysql:
    image: mysql:8.4
    container_name: fullstack-challenge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
      MYSQL_USER: clinic
      MYSQL_PASSWORD: clinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: