/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre um atendimento, que aguarda o protocolo como PENDING */
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendances/{id}/renewals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abre um novo atendimento para o paciente de um atendimento já encerrado
         * @description Aceito só quando o atendimento informado está COMPLETED ou FAILED.
         */
        post: operations["renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attendances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta o atendimento; o protocolo aparece quando o status é COMPLETED */
        get: operations["findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OpenAttendanceRequest: {
            /** @example Maria da Silva */
            patientName: string;
            /**
             * @description Só dígitos ou no formato 000.000.000-00
             * @example 52998224725
             */
            cpf: string;
        };
        /** @description Erro no formato RFC 9457 */
        ApiProblem: {
            /** @example Dados inválidos */
            title: string;
            /**
             * Format: int32
             * @example 400
             */
            status: number;
            /** @example Corrija os campos indicados. */
            detail?: string;
            /** @example /api/attendances */
            instance?: string;
            /**
             * @description Só em erros de validação: a mensagem de cada campo inválido
             * @example {
             *       "cpf": "CPF inválido"
             *     }
             */
            errors?: {
                [key: string]: string;
            };
        };
        AttendanceResponse: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /** @example Maria da Silva */
            patientName: string;
            /** @example ***.982.247-** */
            maskedCpf: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
            /**
             * @description Presente só quando o status é COMPLETED
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            protocol?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAttendanceRequest"];
            };
        };
        responses: {
            /** @description Atendimento aberto */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponse"];
                };
            };
            /** @description Dados inválidos; o campo errors traz a mensagem de cada um */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description O CPF já tem um atendimento em andamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    renew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Novo atendimento aberto */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponse"];
                };
            };
            /** @description Atendimento não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
            /** @description O paciente ainda tem um atendimento em andamento */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Atendimento encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponse"];
                };
            };
            /** @description Atendimento não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiProblem"];
                };
            };
        };
    };
}
