spring.application.name=fullstack-challange

spring.datasource.url=jdbc:mysql://localhost:3306/clinic
spring.datasource.username=clinic
spring.datasource.password=clinic

spring.jpa.hibernate.ddl-auto=none